import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner";
import { CreditCard, Check, Zap, Crown, ChevronRight, Receipt, Calendar } from "lucide-react";
import { motion } from "framer-motion";
import { Switch } from "@/components/ui/switch";
import DashboardSidebar from "@/components/dashboard/DashboardSidebar";
import MobileSidebar from "@/components/dashboard/MobileSidebar";
import { useUserPlan } from "@/hooks/useUserPlan";
import { trackPlanUpgrade, trackButtonClick } from "@/lib/analytics";

const Billing = () => {
  const navigate = useNavigate();
  const [user, setUser] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [isLifetime, setIsLifetime] = useState(false);
  const { plan, isFree, isStarter, isPro } = useUserPlan();

  useEffect(() => {
    const checkUser = async () => {
      const { data: { session } } = await supabase.auth.getSession();
      if (!session) {
        navigate("/auth");
        return;
      }

      const { data: { user } } = await supabase.auth.getUser();
      setUser(user);
      setLoading(false);
    };

    checkUser();
  }, [navigate]);

  const plans = [
    {
      name: "Free",
      price: 0,
      period: "forever",
      icon: Zap,
      color: "from-gray-500 to-gray-600",
      features: [
        "3 email generations / month",
        '"Generated by Vayno" watermark',
        "Smart Preview",
        "Basic email templates"
      ]
    },
    {
      name: "Starter",
      price: 12,
      period: "month",
      icon: CreditCard,
      color: "from-primary to-accent",
      popular: true,
      showToggle: true,
      lifetimePrice: 89,
      features: [
        "50 email generations / month",
        "Remove watermark",
        "Smart Preview",
        "Priority AI speed",
        "Everything in Free",
        "Email support"
      ]
    },
    {
      name: "Pro",
      price: 29,
      period: "month",
      icon: Crown,
      color: "from-accent to-primary",
      features: [
        "500 email generations / month",
        "Auto-Translate",
        "Everything in Starter",
        "Priority AI & early access",
        "Priority support & dedicated account manager"
      ]
    }
  ];

  const getCurrentPlanName = () => {
    if (isFree) return "Free";
    if (isStarter) return "Starter";
    if (isPro) return "Pro";
    return "Free";
  };

  const handleCheckout = (checkoutUrl: string) => {
    if (user?.id) {
      const urlWithUserId = `${checkoutUrl}&checkout[custom][user_id]=${user.id}`;
      window.open(urlWithUserId, '_blank');
    } else {
      window.open(checkoutUrl, '_blank');
    }
  };

  const handleUpgrade = (planName: string) => {
    const checkoutUrls: { [key: string]: string } = {
      'Starter': isLifetime 
        ? 'https://vayno.lemonsqueezy.com/buy/b9b0bdea-ddc5-42b8-8abc-aee080f88fae?logo=0'
        : 'https://vayno.lemonsqueezy.com/buy/b1c6e286-36a9-4b48-bc80-9b03182d3b83?logo=0',
      'Pro': 'https://vayno.lemonsqueezy.com/buy/b8a3207d-80e9-4092-8cfc-5f15c00511b1?logo=0'
    };

    const checkoutUrl = checkoutUrls[planName];
    if (checkoutUrl) {
      const price = planName === 'Starter' ? (isLifetime ? 89 : 12) : 29;
      trackPlanUpgrade(planName, price);
      handleCheckout(checkoutUrl);
    }
  };

  const handleManageSubscription = async () => {
    try {
      const { data: usageData } = await supabase
        .from('user_usage')
        .select('lemonsqueezy_customer_id')
        .eq('user_id', user?.id)
        .single();

      if (usageData?.lemonsqueezy_customer_id) {
        window.open(`https://app.lemonsqueezy.com/my-orders`, '_blank');
      } else {
        toast.error('No subscription found');
      }
    } catch (error) {
      toast.error('Failed to open subscription management');
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary" />
      </div>
    );
  }

  return (
    <div className="flex min-h-screen bg-background">
      <DashboardSidebar />
      
      <div className="flex-1 flex flex-col">
        {/* Top Bar */}
        <div className="sticky top-0 z-40 border-b border-border/40 glass-card">
          <div className="flex items-center justify-between px-6 py-4">
            <div className="flex items-center gap-4">
              <MobileSidebar />
              <div>
                <h1 className="text-2xl font-bold tracking-tight">Billing & Plans</h1>
                <p className="text-sm text-muted-foreground">Manage your subscription and payment methods</p>
              </div>
            </div>
          </div>
        </div>

        {/* Main Content */}
        <div className="flex-1 overflow-y-auto p-6">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="max-w-6xl mx-auto space-y-8"
          >
            {/* Current Plan Card */}
            <Card className="glass-card p-6 border-primary/20">
              <div className="flex items-start justify-between">
                <div>
                  <div className="flex items-center gap-3 mb-2">
                    <h2 className="text-xl font-semibold">Current Plan</h2>
                    <Badge variant="secondary" className="bg-primary/10 text-primary">
                      {getCurrentPlanName()}
                    </Badge>
                  </div>
                  <p className="text-sm text-muted-foreground">
                    {isFree && "You're on the free plan. Upgrade to unlock more features and remove watermarks."}
                    {isStarter && "You're on the Starter plan. Upgrade to Pro for batch campaigns and more."}
                    {isPro && "You're on the Pro plan with full access to all features."}
                  </p>
                </div>
                <div className="flex gap-2">
                  {!isFree && (
                    <Button variant="outline" onClick={handleManageSubscription}>
                      <CreditCard className="w-4 h-4 mr-2" />
                      Manage Subscription
                    </Button>
                  )}
                  {!isPro && (
                    <Button onClick={() => handleUpgrade(isStarter ? "Pro" : "Starter")}>
                      <Crown className="w-4 h-4 mr-2" />
                      Upgrade Now
                    </Button>
                  )}
                </div>
              </div>

              <Separator className="my-6" />

              <div className="grid gap-4 md:grid-cols-3">
                <div className="p-4 rounded-lg bg-muted/30">
                  <div className="flex items-center gap-2 mb-2">
                    <Receipt className="w-4 h-4 text-muted-foreground" />
                    <p className="text-sm font-medium">Billing Cycle</p>
                  </div>
                  <p className="text-lg font-semibold">
                    {isFree ? "No active subscription" : "Monthly"}
                  </p>
                </div>

                <div className="p-4 rounded-lg bg-muted/30">
                  <div className="flex items-center gap-2 mb-2">
                    <Calendar className="w-4 h-4 text-muted-foreground" />
                    <p className="text-sm font-medium">Next Billing Date</p>
                  </div>
                  <p className="text-lg font-semibold">
                    {isFree ? "—" : new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
                  </p>
                </div>

                <div className="p-4 rounded-lg bg-muted/30">
                  <div className="flex items-center gap-2 mb-2">
                    <CreditCard className="w-4 h-4 text-muted-foreground" />
                    <p className="text-sm font-medium">Payment Method</p>
                  </div>
                  <p className="text-lg font-semibold">
                    {isFree ? "None" : "•••• 4242"}
                  </p>
                </div>
              </div>
            </Card>

            {/* Available Plans */}
            <div>
              <h2 className="text-2xl font-bold mb-6">Available Plans</h2>
              <div className="grid gap-6 md:grid-cols-3">
                {plans.map((planItem, index) => {
                  const Icon = planItem.icon;
                  const isCurrentPlan = planItem.name.toLowerCase() === plan;
                  
                  return (
                    <motion.div
                      key={planItem.name}
                      initial={{ opacity: 0, y: 20 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ delay: index * 0.1 }}
                    >
                      <Card className={`glass-card p-6 border-primary/20 relative overflow-hidden ${planItem.popular ? 'ring-2 ring-primary' : ''}`}>
                        {planItem.popular && (
                          <div className="absolute top-0 right-0 bg-primary text-primary-foreground text-xs font-medium px-3 py-1 rounded-bl-lg">
                            POPULAR
                          </div>
                        )}

                        <div className={`w-12 h-12 rounded-xl bg-gradient-to-br ${planItem.color} flex items-center justify-center mb-4`}>
                          <Icon className="w-6 h-6 text-white" />
                        </div>

                        <h3 className="text-2xl font-bold mb-2">{planItem.name}</h3>
                        
                        <div className="mb-6">
                          <span className="text-4xl font-bold">
                            ${planItem.showToggle && isLifetime && planItem.lifetimePrice ? planItem.lifetimePrice : planItem.price}
                          </span>
                          <span className="text-muted-foreground">
                            /{planItem.showToggle && isLifetime ? 'one-time' : planItem.period}
                          </span>
                        </div>

                        {planItem.showToggle && (
                          <div className="flex items-center gap-3 p-3 rounded-xl bg-secondary/50 mb-6">
                            <span className={!isLifetime ? 'font-medium text-sm' : 'text-muted-foreground text-sm'}>Monthly</span>
                            <Switch checked={isLifetime} onCheckedChange={setIsLifetime} />
                            <span className={isLifetime ? 'font-medium text-sm' : 'text-muted-foreground text-sm'}>Lifetime</span>
                          </div>
                        )}

                        <Button
                          className="w-full mb-6" 
                          variant={isCurrentPlan ? "outline" : "default"}
                          disabled={isCurrentPlan || planItem.name === "Free"}
                          onClick={() => {
                            if (planItem.name === "Free") return;
                            handleUpgrade(planItem.name);
                          }}
                        >
                          {isCurrentPlan ? "Current Plan" : planItem.name === "Free" ? "Current Plan" : "Upgrade"}
                          {!isCurrentPlan && planItem.name !== "Free" && <ChevronRight className="w-4 h-4 ml-2" />}
                        </Button>

                        <Separator className="mb-4" />

                        <ul className="space-y-3">
                          {planItem.features.map((feature) => (
                            <li key={feature} className="flex items-start gap-2">
                              <Check className="w-5 h-5 text-primary shrink-0 mt-0.5" />
                              <span className="text-sm">{feature}</span>
                            </li>
                          ))}
                        </ul>
                      </Card>
                    </motion.div>
                  );
                })}
              </div>
            </div>

            {/* Billing History */}
            <Card className="glass-card p-6 border-primary/20">
              <h2 className="text-xl font-semibold mb-4">Billing History</h2>
              <p className="text-sm text-muted-foreground mb-4">
                Your payment history and invoices will appear here once you upgrade to a paid plan.
              </p>
              
              {!isFree && (
                <div className="space-y-3">
                  {[1, 2, 3].map((i) => (
                    <div key={i} className="flex items-center justify-between p-4 rounded-lg bg-muted/30">
                      <div className="flex items-center gap-3">
                        <Receipt className="w-5 h-5 text-muted-foreground" />
                        <div>
                          <p className="text-sm font-medium">
                            {plan.charAt(0).toUpperCase() + plan.slice(1)} Plan - Monthly
                          </p>
                          <p className="text-xs text-muted-foreground">
                            {new Date(Date.now() - i * 30 * 24 * 60 * 60 * 1000).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
                          </p>
                        </div>
                      </div>
                      <div className="flex items-center gap-4">
                        <Badge variant="secondary" className="bg-green-500/10 text-green-500">
                          Paid
                        </Badge>
                        <Button variant="ghost" size="sm">
                          Download
                        </Button>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </Card>
          </motion.div>
        </div>
      </div>
    </div>
  );
};

export default Billing;
